name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '5 2 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data
      run: |-
        curl "https://data.cityofnewyork.us/api/views/5vr7-5fki/rows.csv?accessType=DOWNLOAD" | sort -t ',' -k 4 -n > nypd-personnel-demographics.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
